### ISSUE TITLE
Error on watch mode

### ISSUE THREAD

**Issue by sakaeda11** [tradingview/webpack-uglify-parallel#7]
I face the "Cannot read property 'send' of undefined" error as follows.
--------
91% additional asset processing/*****/node_modules/webpack-uglify-parallel/index.js:72
				plugin.nextWorker().send({
				                   ^

TypeError: Cannot read property 'send' of undefined
    at /*****/node_modules/webpack-uglify-parallel/index.js:72:24
    at Array.forEach (native)
    at Compilation.<anonymous> (/*****/node_modules/webpack-uglify-parallel/index.js:54:10)
    at Compilation.applyPluginsAsyncSeries (/*****/node_modules/tapable/lib/Tapable.js:206:13)
    at self.applyPluginsAsync.err (/*****/node_modules/webpack/lib/Compilation.js:657:10)
    at next (/*****/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin.callback (/*****/node_modules/webpack/lib/ProgressPlugin.js:115:6)
    at Compilation.applyPluginsAsyncSeries (/*****/node_modules/tapable/lib/Tapable.js:206:13)
    at sealPart2 (/*****/node_modules/webpack/lib/Compilation.js:653:9)
    at next (/*****/node_modules/tapable/lib/Tapable.js:202:11)
    at Compilation.compilation.plugin (/*****/node_modules/webpack/lib/ProgressPlugin.js:111:6)
    at Compilation.applyPluginsAsyncSeries (/*****/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (/*****/node_modules/webpack/lib/Compilation.js:596:8)
    at applyPluginsParallel.err (/*****/node_modules/webpack/lib/Compiler.js:514:17)
    at /*****/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/*****/node_modules/webpack/lib/Compilation.js:498:11)
    at processModuleDependencies.err (/*****/node_modules/webpack/lib/Compilation.js:468:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! *****@1.0.0 build-js: `webpack --config webpack.config.prod.js --progress --colors --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the *****@1.0.0 build-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /*****/.npm/_logs/2017-10-11T02_31_50_705Z-debug.log
--------

- My project has many entry point.
- I use Webpack as watch mode.
- This error does not occur on first build, but occurs on modifying typescript code and rebuild by watch mode.

Is there any solution?
Regards

**Comment by Nelson-Ning** [comment]
Have you solved this problem?

**Comment by Xia-Ao** [comment]
Have you solved this problem?
